version: '3.8'
services:
  api01: &api
    image: sonederbr/rinha-api
    build: ./
    hostname: api01
    environment:
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    ports:
      - "8081:8080"
    depends_on:
      - db
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "50MB"
  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: "50MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=RinhaBackend2024Q1
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=300' -c 'fsync=off' -c 'synchronous_commit=off' -c 'checkpoint_timeout=1d' -c 'full_page_writes=false'
    # command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.75"
    #       memory: "400MB"

networks:
  default:
    driver: bridge
    name: nw-rinha
