version: '3.8'
services:
  api01: &api
    image: sonederbr/rinha-api
    build: ./\
    hostname: api01
    environment:
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    ports:
      - "8081:8080"
    depends_on:
      - db
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"
    #       memory: "130MB"
  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.15"
    #       memory: "20MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=RinhaBackend2024Q1
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.95"
    #       memory: "270MB"

networks:
  default:
    driver: bridge
    name: nw-rinha